# Generated by Django 2.0.6 on 2018-06-22 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_belt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quotes',
            new_name='Quote',
        ),
    ]
